id: A83F416EE
title: Aspiration for the Spread of the Teachings
type: translation
pechas:
- I4912B2A3
- IF9F4F2AE
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:06:40.842678
  last_modified_at: 2023-01-04 12:06:40.842692
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I4912B2A3/CF72: 91C1
  IF9F4F2AE/F704: 91C1
